version: '3.8'

services:
  frontend:
    build: .
    container_name: oakbridge_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
